name: Frédéric Ranft
favicon: null
layout_spectrum: 0.50229
typography_spectrum: 0.02022
title: f_ranft
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0f0f0'
    - '#4042df'
    - '#696af3'
    - '#8f91f5'
    - '#d0d8fd'
  brandStrength: 0
  lightness: 0.9375
  saturation: 0
  rhythmicContrast: 1
purpose: []
